formations = [
    ("2016", "DSI HSBC Software delivery"),
    # Ajouter des entrées de formation
    ("2014", "DSI CNP assurance Production informatique et gestion des produits financiers"),
    ("2014", "DSI Société générale SGSS AMOA suivi de projets financiers"),
    ("2011", "DSI Société générale SGSS AMOA suivi de projets financiers"),
    ("2010", ""), # Accolades vides pour cette entrée manquante
    ("2009", "DSI Caisse des dépôts AMOA et Assistant projet")
]
competences = {
    "Logiciels & Compétences": [
        "Gestion de la production informatique",
        "Épargne salariale",
        "Coordination de mise en œuvre des aspects fonctionnels et techniques",
        "Qualité et pertinence des données des systèmes d'information et de communication",
        "Mise en place de tableaux de bord de la qualité des données",
        "Traitement des anomalies en lien avec les équipes informatiques",
        "Mise à jour et diffusion des référentiels fonctionnels",
        "Communication sur les référentiels",
        "Animation du réseau des utilisateurs",
        "Propositions d'amélioration des processus",
        "Liaison avec les systèmes d'information fournisseurs et clients",
        "Pilotage de l'activité de vérification comptable via l'outil Statcom avant diffusion",
        "Analyse des statistiques",
        "Mise en place d'un contrôle qualité",
        "Aide aux équipes pour cerner et formuler les besoins",
        "Trouver la meilleure solution en fonction des critères soumis",
        "Pilotage du projet sur la partie fonctionnelle jusqu'à la conduite du changement",
        "Réalisation des diagnostics et des schémas directeurs",
        "Mise en place de bonnes pratiques agiles",
        "Accompagnement des équipes pour des transformations digitales agiles",
        "AS400 (traitement contrats prévoyance)",
        "Grapht Talk AIA",
        "JIRA SD",
        "Graph Talk AIA (AS400 technique et fonctionnel)",
        "Gestion des projets assurance-vie",
        "AMOA/BA et paramétrage produits Assurance-vie",
        "Préparation et envoi de points opérationnels quotidiens",
        "Cadrage, recueil et analyse des besoins métiers",
        "Choix des solutions et mise en place et animation d'ateliers fonctionnels",
        "Analyse de l'existant, études d'impacts et modélisation des processus métiers",
        "Élaboration du back log et priorisation des besoins",
        "Définition de la stratégie de recette et réalisation de la recette",
        "Assistance dans l'analyse des problèmes de production et contribution à leur résolution",
        "Accompagnement dans le changement et organisation des formations",
        "Participation au conseil et conception de systèmes d'information",
        "Documentation des informations requises",
        "Protection des bases de données et gestion des risques",
        "Gestion et Management des Applications",
        "Conformité Gestion avancée des périphériques amovibles",
        "Prévention de la fuite de données",
        "Gestion de patch et application",
        "MS STUDIO-FEEBOX-Télélogic-Prestex/Infocentre-Harmonie-MasterA-Business Object",
        "Technologies: JIRA bug, MS Project, MS Studio",
        "Analyste fonctionnel outils de reporting RMP",
        "Préparation et envoi de points opérationnels quotidiens",
        "Validation et rédaction des Users Stories",
        "Participation à la stratégie de recette",
        "Rédaction de scénarios et plans de tests",
        "Mise à jour des référentiels des améliorations traitées",
        "Participation aux études de la Digital Factory",
        "Outils métiers de conception de packs et allocations",
        "Suivi de production et analyse des incidents structurants",
        "Études d'impacts sur évolutions métiers transverse",
        "Contribution aux études transverses",
        "Technologies: RMP reporting, Access, pack office, MS Office (Excel, Word, PowerPoint, Visio), Reporting d'activité, Access",
        "AMOA suivi de projets financiers",
        "Création et suivi des produits financiers",
        "Assistance à la maîtrise d'ouvrage et gestion de projet",
        "Étude de cadrage et assistance au choix de solutions applicatives",
        "Mise en œuvre des systèmes d'information de comptabilité OPCVM et de reporting",
        "Optimisation ou refonte de processus",
        "Pilotage et suivi de projet",
        "Formalisation d'expressions de besoins",
        "Définition de plans de tests",
        "Réalisation et conduite de recette fonctionnelle et de tests d'intégration",
        "Organisation de migrations de données",
        "Conduite du changement",
        "IGEFI-ARIANE-SEGP-SITI prod et préprod-bloomberg",
        "Technologies: SITI prod et préprod, Bloomberg",
        "AMOA et Assistant projet",
        "Suivi des investissements et gestion des dossiers financiers pour divers projets",
        "Conduite de projets systèmes d'information",
        "Rédaction de cahiers des charges et choix des solutions",
        "Organisation des projets SI",
        "Pilotage des processus dans le cycle de vie d'un projet",
        "Assistance fonctionnelle aux métiers",
        "Administration fonctionnelle des systèmes",
        "Suivi des contrats de maintenance des SI"
    ]
}
experiences = [
    ("DSI HSBC Software delivery", "Septembre 2014 - Août 2016", "Gestion de la prod informatique et épargne salariale",
     [
         "Assurer la coordination de la mise en œuvre des aspects fonctionnels et techniques.",
         "Mettre en place des tableaux de bord de la qualité des données, traiter les anomalies en lien avec les équipes informatiques, mettre à jour et diffuser les référentiels fonctionnels.",
         "Communication sur les référentiels, animation du réseau des utilisateurs, propositions d'amélioration des processus.",
         "Liaison avec les systèmes d'information fournisseurs et clients, pilotage de l’activité de vérification comptable via l’outil Statcom avant diffusion, analyser des statistiques, mettre en place un contrôle qualité.",
         "Aider les équipes à cerner les besoins, trouver la meilleure solution en fonction des critères, pilotage du projet sur la partie fonctionnelle jusqu’à la conduite du changement, réalisation des diagnostics, des schémas directeurs et mise en place de bonnes pratiques agiles, accompagner les équipes dans le cadre de transformations digitales agiles."
     ], ["AS400", "Graph Talk AIA", "Statcom", "JIRA", "SD"]),
    ("DSI CNP assurance Production informatique et gestion des produits financiers", "Juin 2013 - Juin 2014", "Analyste fonctionnel outils de reporting RMP",
     [
         "Préparation et envoi de points opérationnels quotidiens.",
         "Participation à la validation et rédaction des Users Stories en collaboration avec différents métiers.",
         "Analyse de l’existant, études d'impacts et modélisation des processus métiers, contribution à l'élaboration du back log et à la priorisation des besoins.",
         "Participation à la définition de la stratégie de recette, réalisation du suivi et de la validation de correction des anomalies de recette déclarées.",
         "Contribution aux études transverses de la Digital Factory."
     ], ["RMP reporting", "Access", "pack office"]),
    ("DSI Société générale SGSS AMOA suivi de projets financiers", "Janvier 2011 - Juin 2014", "Production-gestion des produits financiers-: Assistance à la maîtrise d’ouvrage (AMOA) et de gestion de projet dans le cadre de projets de transformation de la fonction comptable OPCVM et financière.",
     [
         "Préparation et envoi de points opérationnels quotidiens.",
         "Etude de cadrage et assistance au choix de solutions applicatives, mise en œuvre et adaptation des systèmes d’information dans le cadre d’évolutions réglementaires et organisationnelles.",
         "Assistance au pilotage et au suivi de projet, planification, coordination, organisation et animation de comités, conduite du changement."
     ], ["IGEFI", "ARIANE", "SEGP", "Bloomberg", "SITI prod", "SITI préprod", "MS Project", "GANTT"])
]

